CREATE TABLE COMPANY(
	ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	NAME VARCHAR(128) NOT NULL,
	FACE VARCHAR(128),
	EMAIL VARCHAR(512),
	PHONE VARCHAR(256),
	SITE VARCHAR(64),
	CONSTRAINT primary_key PRIMARY KEY (ID)
);

